### PR TITLE
Here is a much more recent list of Python Talks

### PR DESCRIPTION
**Pull request by PythonLinks**
Thank you for the wonderful Pandas library. 

For the growth of the Panda's ecosystem, it is very important to have a good collection of recent human-curated videos of technical talks, organized by subject category.  I have built and am continuing to improve and maintain this list.  

I apologize for deleting the older talks, but as a curator of technical videos, I have found that it is best to provide people with fresher content.  

Marc mentioned that a new website will be coming online soon, but in the meantime for a few weeks, this will be a small improvement to your website. 

Your comments on this pull request are most welcome.

### CODE REVIEW

**Comment by wesm** [comment]
This is sort of weird. Why not maintain a comprehensive list of talks and videos about the project rather than providing an opinionated subset?

**Comment by PythonLinks** [comment]
Thank you for asking.   Forgive me if not everything is yet included in these lists.  One has to start somewhere.  I am working on creating a more comprehensive list.  Here are the conferences I have catalogued so far.  https://pythonlinks.info/conferences-and-channels

Here are the conferences I will be cataloguing in the near future. 
https://pythonlinks.info/conferences-to-be-indexed

Are there any other particularly good talks which you think I should include right away?

While the page shows the top 10 Pandas talks, the site is organized as a tree.   You can swipe up, or use your arrow keys to go down, and visit the child nodes.  Try clicking on the list view.  The introductory video is helpful in understanding the content. 


There is so much stuff on the web.  Some of it is quite old.  Some of it has a lot of down votes. I am generally starting with the largest most competitive conferences, and expanding from there.  While I do not yet include everything, I hope that this list is an valuable addition to  the Panda's community.  

Does that answer your question?

Warm Regards
Christopher Lozinski

**Comment by wesm** [comment]
Seems like creating a reverse chronological list of talks given by members of the pandas community or at major Python conferences (PyCon, SciPy, PyData) would be the right place to start. A shorter list of "popular talks" could be prepared for people not interested in the comprehensive list

**Comment by PythonLinks** [comment]
> at major Python conferences (PyCon, SciPy, PyData) 

That is my focus. 

>given by members of the pandas community

I am happy to add in other talks by people you recommend.  Actually the top of the charts, overall,  is currently a talk on Pandas given by Marc at a PyData London Meetup.  Usually I would not cover meetups. 
 The only reason I knew about it, is because he recommended it.  But it sure has a lot of upvotes, and not a single downvote.  So I added it. 

> Seems like creating a reverse chronological list of talks would be the right place to start. 

It should be pretty easy for me to sort the talks by date.  I used to do that, before moving to upvotes.  I could easily do it again.  Really all three views are needed.  Give me  best talks in this branch of the tree by upvotes (Best view).   Give me the most recent talks on this branch of the tree (Recent View).   Give me the talks on this node of the tree (List View). 

How far back do you want to go?  PyVideo.org has 100 talks on Pandas. 
https://pyvideo.org/search.html?q=pandas
All the way back to 2013.   But only 1 talk from 2018. ( I already have 8 from 2018.)  My focus is first to get all the talks from the best conferences in 2018,  and then I can start pulling in more from 2017 from PyVideo.  At that point I should add the year next to the talk.   Do you want me to go back further than 2017?  

> A shorter list of "popular talks" could be prepared for people not interested in the comprehensive list

That is what I have.  The 10 best talks on Pandas.   Also the 4 best advanced pandas talks
https://pythonlinks.info/pandas/advanced-pandas-talks

The categories will grow and evolve over time. 

You could prepare it yourself.  The problem is in maintaining it.  There is always a new conference.  The best talks change over time.  By using my list, you get rid of the maintenance hassle.  The truth is that no one was maintaining your list.  What I am volunteering to do is to maintain the list.  I have the software for importing a whole conference at a time and  categorizing the talks. .  It only takes a few seconds to get the current votes from YouTube.  And the website makes it easy for users to discover other valuable open source projects and start using them. 

Would this information be useful to your readers?

Warm Regards
Christopher Lozinski

**Comment by datapythonista** [comment]
I don't think we're planning to merge this, and in the new pandas website my proposal is to avoid maintaining lists of talks, tutorials or other resources (which are very welcome to exist in other websites than the ones we maintain).

**Pull request closed without merging**
