### PR TITLE
Update for 0.21.1

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by TomAugspurger** [comment]
cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
I think you need to update `previous.rst` as well (BTW, maybe easier would be to have a single file with the two latest releases, so it is just in that single file you can remove the oldest and add a new one)

**Comment by TomAugspurger** [comment]
I couldn't remember, but I thought the idea was to have the latest version of the two most recent releases on the main page. So now we'll have

1. 0.21.1: the latest in the 0.21 line
2. 0.20.3: The latest in the 0.20.3 line

When we do 0.22.0, I'll move the current `latest.rst` to `previous.rst`.

**Comment by TomAugspurger** [comment]
Obviously, we can change that policy to do whatever we want, but I think that's what we (I?) decided on last time.

**Comment by jorisvandenbossche** [comment]
The times before you did it differently in any case .. :-) See eg https://github.com/pandas-dev/pandas-website/commit/337e3bb5e635abd3b7acbe43f02bf5ba2fb23a94#diff-db4b047b30ffef7855b12b527860ac2c

Anyhow, I think it is more informative for users to keep the announcement and highlights of 0.21.0 visible rather than the announcement of 0.20.3

**Comment by TomAugspurger** [comment]
Ha, you're correct again :)

Was I getting it mixed up with the sidebar? Should 0.21.0 be removed from the sidebar, now that it's not the latest?

**Comment by jorisvandenbossche** [comment]
So maybe logic could be:

- if doing small release: keep last big release in previous.rst, update latest.rst with the small release
- if doing big release: move latest small release to previous.rst, update latest.rst with big release

Does that makes sense?

**Comment by jorisvandenbossche** [comment]
> Was I getting it mixed up with the sidebar? Should 0.21.0 be removed from the sidebar, now that it's not the latest?

Yeah, maybe? Although maybe 0.21.0 can still be mentioned in the previous releases box until there is a new latest release, that's OK I think.

**Pull request merged**
