### PR TITLE
Update institutional partners

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jreback** [comment]
lgtm

**Comment by TomAugspurger** [comment]
@jorisvandenbossche here you go 
anaconda_horizontal_rgb

**Comment by TomAugspurger** [comment]
Forgot I could push :) I added the logo. Are you OK with the layout?

screen shot 2017-09-19 at 11 19 56 am

Vertical spacing is a bit weird, but I'm not sure how to control that with reST.

**Comment by jorisvandenbossche** [comment]
> Are you OK with the layout?

It's not a fantastic layout, but just as bad as the rest of the page (I made it :-)). Somebody with more sphinx/theming/css skills and time can improve it, but that is for a separate PR.

**Pull request merged**
